{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeai.backend.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeai.backend.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, create, delete, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, delete]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, list, watch, create, update, delete]
  - apiGroups: [""]
    resources: [resourcequotas]
    verbs: [get, list, create, update, delete]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, create, update, delete]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings]
    verbs: [get, list, create, update, delete]
  - apiGroups: [batch.volcano.sh]
    resources: [jobs]
    verbs: [get, list, create, delete, watch]
  - apiGroups: [scheduling.volcano.sh]
    resources: [queues, podgroups]
    verbs: [get, list]
  - apiGroups: [serving.kserve.io]
    resources: [inferenceservices]
    verbs: [get, list, create, delete, patch, watch]
  - apiGroups: [keda.sh]
    resources: [scaledobjects]
    verbs: [get, list, create, delete, patch]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeai.backend.fullname" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeai.backend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeai.backend.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
